### ISSUE TITLE
Streaming data in chunks

### ISSUE THREAD

**Issue by ilackarms** [thisismydesign/json-streamer#4]
Since json-streamer is based on json-stream, is it possible to do something like the following example from JSON:Stream:

```ruby
def receive_data(data)
  begin
    @parser << data
  rescue JSON::Stream::ParserError => e
    close_connection
  end
end
```

The reason that I ask is that the JSON I am parsing is not from a file, but a chunked HTTP Response. Thanks!

**Comment by thisismydesign** [comment]
I think so. I wrapped a similar implementation in a way that Json::Streamer expects an IO object which it will use this way:

> file_io.each(@chunk_size) do |chunk|
>   parser << chunk
> end

(The naming `file_io` is actually misleading in this case.)

You can pass any IO objects to initialize. Let me know if you managed to try it.

**Comment by ilackarms** [comment]
unfortunately I don't have access to an IO object. Here's what my code looks like:

```ruby
block = proc do |response|
  response.read_body do |chunk|
    #process each chunk here
    parser << chunk
  end
end

RestClient::Request.new(
   headers: {},
   method: :get,
   url: 'http://localhost:8001/',
   block_response: block
).execute
```

**Comment by thisismydesign** [comment]
What does `response.read_body` return when not passed to a block? It may be possible to simply pass `response.read_body`. If not then I'd try to introduce an IO object that receives the chunks and is passed to Json::Streamer.

It should also be possible to extend the API to provide support for JSON::Stream-like usage but it is my strong feeling that your use-case can be solved with the current API as well. Nevertheless I'll add it to the wish list but can't promise any timeframe at the moment.

**Comment by thisismydesign** [comment]
Any updates on this?

**Comment by thisismydesign** [comment]
As per Pull #5 release [v1.1.0](https://github.com/thisismydesign/json-streamer/releases/tag/v1.1.0) contains support for `JSON:Stream` or `EventMachine` style input. For examples take a look at the [README](https://github.com/thisismydesign/json-streamer#eventmachine-style-input-since-110) or [unit tests](https://github.com/thisismydesign/json-streamer/blob/a71c8a7d59c004f0fca8d1d45e13e1e6acff53bd/spec/json/streamer/json_streamer_spec.rb) with the following contexts: `1st level from EventMachine style input` or `1st level from EventMachine style chunked input`.

**Comment by ilackarms** [comment]
Tested and it works for my use case. Thanks!
